openapi: 3.0.1
info:
  title: Emergency Alerts
  description: This applications monitor the users' location in order to send them alerts about possible emergencies in their area.
  version: '1.0'
  termsOfService: 'https://emergencies.spilab.es/terms'
  contact:
    name: Emergency Alerts
    url: 'https://spilab.es'
    email: info@spilab.es
paths:
  /emergency:
    post:
      tags:
        - Emergencies
      summary: Sends an emergency to the devices
      description: An emergency is sent to the devices and shown to the users inside the emergency area
      operationId: postEmergency
      requestBody:
        description: Information about the emergency
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Emergency'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmergencyResponse'
        '404':
          $ref: '#/components/responses/404NotFound'
  /location:
    get:
      tags:
        - Location
      summary: Gets the user's location
      description: The user's location is provided
      operationId: getLocation
      parameters:
        - name: latitude
          in: query
          required: true
          schema:
            type: number
            format: double
        - name: longitude
          in: query
          required: true
          schema:
            type: number
            format: double
        - name: radius
          in: query
          required: true
          schema:
            type: number
            format: double
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
        '404':
          $ref: '#/components/responses/404NotFound'
components:
  schemas:
    Emergency:
      required:
        - id
        - title
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        latitude:
          type: number
          format: double
        longitude: 
          type: number
          format: double
        radius:
          type: number
          format: double
    EmergencyResponse:
      properties:
        deviceId:
          type: number
        emergencyId:
          type: integer
          format: int64
        latitude:
          type: number
          format: double
        longitude: 
          type: number
          format: double
    Location:
      properties:
        deviceId:
          type: number
        latitude:
          type: number
          format: double
        longitude: 
          type: number
          format: double
  responses:
    404NotFound:
      description: Not found response
      content:
        text/plain:
          schema:
            title: Endpoint not found
            type: string
            example: Not found
